Website_BanSachAT/Areas/Admin/Controllers/ChuDeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Website_BanSachAT.Models;
using PagedList;
using PagedList.Mvc;
using System.IO;

namespace Website_BanSachAT.Areas.Admin.Controllers
{
    public class ChuDeController : Controller
    {
        SachOnlineDataContext data = new SachOnlineDataContext();
        // GET: Admin/ChuDe
        public ActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public JsonResult DsChuDe()
        {
            try
            {
                var dsCD = (from cd in data.CHUDEs select new { MaCD = cd.MaCD, TenCD = cd.TenChuDe }).ToList();
                return Json(new { code = 200, dsCD = dsCD, msg = "Lấy danh sách chủ đề thành công" }, JsonRequestBehavior.AllowGet);
                    
            }
            catch(Exception ex)
            {
                return Json(new { code = 500, msg = "Lấy danh sách chủ đề thất bại" + ex.Message }, JsonRequestBehavior.AllowGet);
            }
        }
        public JsonResult Details(int MaCD)
        {
            try
            {
                var cd = (from s in data.CHUDEs
                          where (s.MaCD == MaCD) select new { MaCD = s.MaCD, TenChuDe = s.TenChuDe }).SingleOrDefault();
                return Json(new { code = 200, cd = cd, msg = "Lấy thông tin chủ đề thành công" }, JsonRequestBehavior.AllowGet);
            }
           catch(Exception ex)
            {
                return Json(new { code = 500, msg = "Lấy danh sách chủ đề thất bại" + ex.Message }, JsonRequestBehavior.AllowGet);
            }
        }
        public JsonResult AddChuDe(string strTenCD)
        {
            try
            {
                var cd = new CHUDE();
                cd.TenChuDe = strTenCD;
                data.CHUDEs.InsertOnSubmit(cd);
                data.SubmitChanges();
                return Json(new { code = 200, msg = "Thêm chủ đề thành công" }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Json(new { code = 500, msg = "Thêm chủ đề thất bại" + ex.Message }, JsonRequestBehavior.AllowGet);
            }
          
        }
        public JsonResult Update(int MaCD, string strTenCD)
        {
            try
            {
                var cd = data.CHUDEs.SingleOrDefault(c => c.MaCD == MaCD);
                cd.TenChuDe = strTenCD;
                data.SubmitChanges();

                return Json(new { code = 200, msg = "Sửa chủ đề thành công" }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Json(new { code = 500, msg = "Sửa chủ đề thất bại" + ex.Message }, JsonRequestBehavior.AllowGet);
            }
        }
        public JsonResult Delete(int MaCD)
        {
            try
            {
                var cd = data.CHUDEs.SingleOrDefault(c => c.MaCD == MaCD);
                data.CHUDEs.DeleteOnSubmit(cd);
                data.SubmitChanges();

                return Json(new { code = 200, msg = "Xóa chủ đề thành công" }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Json(new { code = 500, msg = "Xóa chủ đề thất bại" + ex.Message }, JsonRequestBehavior.AllowGet);
            }
        }
    }
   
}

Website_BanSachAT/Controllers/BookController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Website_BanSachAT.Models;
using PagedList;
using PagedList.Mvc;

namespace Website_BanSachAT.Controllers
{
    public class BookController : Controller
    {
        SachOnlineDataContext data = new SachOnlineDataContext();
        private List<SACH> LaySachMoi(int count)
        {

            return data.SACHes.OrderByDescending(a => a.NgayCapNhat).Take(count).ToList();
        }
        private List<SACH> SachBanNhieu(int count)
        {
            return data.SACHes.OrderByDescending(a => a.SoLuongBan).Take(count).ToList();
        }
        // GET: Book
        public ActionResult Index (int ? page)
        {
            int iSize = 6;
            var iPageNum = (page ?? 1);
            var listSachMoi = LaySachMoi(20);
            return View(listSachMoi.ToPagedList(iPageNum, iSize));
        }
        public ActionResult SachBanNhieu()
        {
            var listSachBn = SachBanNhieu(6);
            return PartialView(listSachBn);
        }
        [ChildActionOnly]
        public ActionResult NavPartial()
        {
            List<MENU> lst = new List<MENU>();
            lst = data.MENUs.Where(m => m.ParentId == null).OrderBy(m => m.OrderNumber).ToList();
            int[] a = new int[lst.Count()];
            for(int i = 0; i < lst.Count; i++)
            {
                var l = data.MENUs.Where(m => m.ParentId == lst[i].Id);
                a[i] = l.Count();
            }
            ViewBag.lst = a;
            return PartialView(lst);
        }
        [ChildActionOnly]
        public ActionResult LoadChildMenu(int parentId)
        {
            List<MENU> lst = new List<MENU>();
            lst = data.MENUs.Where(m => m.ParentId == parentId).OrderBy(m => m.OrderNumber).ToList();
            ViewBag.Count = lst.Count();
            int[] a = new int[lst.Count()];
            for (int i = 0; i < lst.Count; i++)
            {
                var l = data.MENUs.Where(m => m.ParentId == lst[i].Id);
                a[i] = l.Count();
            }
            ViewBag.lst = a;
            return PartialView("LoadChildMenu", lst);
        }
        public ActionResult TrangTin(string metatitle)
        {
            var tt = (from t in data.TRANGTINs where t.MetaTitle == metatitle select t).Single();
            return View(tt);
        }
        public ActionResult TopicPartial()
        {
            return PartialView();
        }
        public ActionResult TopicPartial_New()
        {
            return PartialView();
        }
        public ActionResult SliderPartial()
        {
            var list = from sl in data.Slides select sl;
            return PartialView(list);
        }
        public ActionResult ChuDepartial()
        {
            var listChuDe = from cd in data.CHUDEs select cd;
            return PartialView(listChuDe);
        }
        public ActionResult SachTheoChuDe(int id, int ? page)
        {
            ViewBag.MaCD = id;
            //tạo biến quy định số sản phẩm trên mỗi trang
            int iSize = 3;
            //tạo biến số trang
            int iPageNum = (page ?? 1);
            var Sach = from s in data.SACHes where s.MaCD == id select s;
            return View(Sach.ToPagedList(iPageNum, iSize));
        }
        public ActionResult NhaXuatBan()
        {
            var listNXB = from xb in data.NHAXUATBANs select xb;
            return PartialView(listNXB);
        }
        public ActionResult SachTheoNXB(int id, int ? page)
        {
            ViewBag.MaNXB = id;
            int iSize = 3;
            int iPageNum = (page ?? 1);
            var Sach = from s in data.SACHes where s.MaNXB == id select s;
            return View(Sach.ToPagedList(iPageNum, iSize));
        }
        public ActionResult ChiTietSach(int id)
        {
            var Sach = from s in data.SACHes where s.MaSach == id select s;
            return View(Sach.Single());
        }
        

    }
}

Website_BanSachAT/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml
<html>
<head>
    <meta charset="utf-8" name="viewport" content="width=device-width, initial-scale=1">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/Scripts/js")
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

</head>
<body style="padding: 0px;">
    <nav class="navbar navbar-inverse ">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                        data-target="#navAdmin" aria-expanded="false">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="@Url.Action("Index","Home")">
                    SachOnline Admin
                </a>
            </div>
            <div class="collapse navbar-collapse" id="navAdmin">
                <ul class="nav navbar-nav">
                    <li><a href="@Url.Action("Index","Book")">QUẢN LÝ SÁCH</a> </li>
                    <li><a href="@Url.Action("Index","ChuDe")">QUẢN LÝ CHỦ ĐỀ</a> </li>
                    <li>
                        <a href="@Url.Action("Index","NhaXuatBan")">
                            QUẢN LÝ NHÀ XUẤTBẢN
                        </a>
                    </li>
                    <li>
                        <a href="@Url.Action("Index","KhachHang")">
                            QUẢN LÝ KHÁCH HÀNG
                        </a>
                    </li>
                    <li>
                        <a href="@Url.Action("Index","DonHang")">QUẢN LÝ ĐƠN HÀNG</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container">
        @RenderBody()
    </div>
    <footer class="container well">
        <div style="text-align:center;">
            <p>ADMIN</p>
        </div>
    </footer>
</body>
</html>